version: '3.1'
services:
  wordpress:
    image: wordpress:6.5.5-apache
    volumes:
     - ./wordpress:/var/www/html 
    restart: always
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpressdb
  mysql:
    image: mysql:8.0.0
    restart: always
    volumes:
     - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

volumes:
  wordpress:
  mysql:
